--- #YAML:1.0
name:               Template-Tiny
version:            0.10
abstract:           Template Toolkit reimplemented in as little code as possible
author:
    - Adam Kennedy <adamk@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    perl:        5.00503
    Test::More:  0.47
resources:
    repository:  http://svn.ali.as/cpan/trunk/Template-Tiny
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
